### ISSUE TITLE
Any workaround for this?

### ISSUE THREAD

**Issue by ricbra** [Algotec/fileReaderTest#1]
Hi @nadavsinai 

Thanks for this nice demo page! Did you ever find a workaround for Chrome? The project I'm currently working on heavily depends on the `FileReader` for hashing chunks before being uploaded, but on Chrome this sooner or later results in memory problems or crashing browsers.

**Comment by nadavsinai** [comment]
@ricbra AFAIK this bug has been fixed with chrome 56, at least with regards to readAsArrayBuffer there is no leak
Chrome memory management is still not very good, at least when comparing to Edge or Firefox. we cap out use of memory to around 1.5GB to avoid crashes.
